name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * * # 8:00AM IST
    - cron: 00 14 * * * # 7:30PM IST
    - cron: 00 06 * * 1-5 # 11:30AM IST Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6.0.1

      - name: Install Nodejs and npm
        uses: actions/setup-node@v6.1.0
        with:
          node-version: '22'

      - name: Install Newman and HTMLExtra Reporter Globally
        run:  | 
              npm install -g newman
              npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with newman
        run: |
             newman run 'Inwarranty-Flow Collection.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testdata.csv \
             -r cli,htmlextra
